insert into Disciplina (codigo_disciplina, nome, ementa, creditos) values ('132IUP', 'Haitian Creole', 'Focused next generation conglomeration', 46);
insert into Disciplina (codigo_disciplina, nome, ementa, creditos) values ('167FTJ', 'Pashto', 'Programmable motivating implementation', 50);
insert into Disciplina (codigo_disciplina, nome, ementa, creditos) values ('764PIY', 'Dari', 'Multi-layered homogeneous portal', 35);
insert into Disciplina (codigo_disciplina, nome, ementa, creditos) values ('980DFH', 'Norwegian', 'Networked tangible throughput', 26);
insert into Disciplina (codigo_disciplina, nome, ementa, creditos) values ('375RKD', 'Norwegian', 'Quality-focused even-keeled collaboration', 46);
insert into Disciplina (codigo_disciplina, nome, ementa, creditos) values ('263CEN', 'Punjabi', 'Synchronised real-time workforce', 23);
insert into Disciplina (codigo_disciplina, nome, ementa, creditos) values ('985IKP', 'Polish', 'Open-source impactful database', 22);
insert into Disciplina (codigo_disciplina, nome, ementa, creditos) values ('374GTC', 'Bosnian', 'Stand-alone heuristic protocol', 39);
insert into Disciplina (codigo_disciplina, nome, ementa, creditos) values ('595SLZ', 'Dhivehi', 'Upgradable 4th generation superstructure', 29);
insert into Disciplina (codigo_disciplina, nome, ementa, creditos) values ('201GUD', 'Catalan', 'Operative bandwidth-monitored superstructure', 48);
insert into Disciplina (codigo_disciplina, nome, ementa, creditos) values ('504EGL', 'Tok Pisin', 'Grass-roots national forecast', 31);
insert into Disciplina (codigo_disciplina, nome, ementa, creditos) values ('466IBZ', 'Aymara', 'Devolved contextually-based system engine', 59);
insert into Disciplina (codigo_disciplina, nome, ementa, creditos) values ('185PZX', 'Armenian', 'Multi-layered attitude-oriented frame', 42);
insert into Disciplina (codigo_disciplina, nome, ementa, creditos) values ('188ZGR', 'Nepali', 'Cross-platform system-worthy collaboration', 37);
insert into Disciplina (codigo_disciplina, nome, ementa, creditos) values ('195FAP', 'Kyrgyz', 'Stand-alone multi-state attitude', 39);
insert into Disciplina (codigo_disciplina, nome, ementa, creditos) values ('246ASD', 'Northern Sotho', 'Distributed coherent encryption', 41);
insert into Disciplina (codigo_disciplina, nome, ementa, creditos) values ('144DFR', 'Zulu', 'Versatile zero administration time-frame', 53);
insert into Disciplina (codigo_disciplina, nome, ementa, creditos) values ('693VXJ', 'Marathi', 'De-engineered well-modulated benchmark', 42);
insert into Disciplina (codigo_disciplina, nome, ementa, creditos) values ('845XUP', 'Hebrew', 'User-friendly exuding core', 47);
insert into Disciplina (codigo_disciplina, nome, ementa, creditos) values ('447KZS', 'Moldovan', 'Down-sized reciprocal capability', 20);
insert into Disciplina (codigo_disciplina, nome, ementa, creditos) values ('045USS', 'Luxembourgish', 'Devolved client-server matrix', 17);
insert into Disciplina (codigo_disciplina, nome, ementa, creditos) values ('680TMS', 'West Frisian', 'Open-architected systemic infrastructure', 42);
insert into Disciplina (codigo_disciplina, nome, ementa, creditos) values ('186EZL', 'Ndebele', 'Reverse-engineered reciprocal concept', 58);
insert into Disciplina (codigo_disciplina, nome, ementa, creditos) values ('052QTO', 'Thai', 'Stand-alone systemic groupware', 44);
insert into Disciplina (codigo_disciplina, nome, ementa, creditos) values ('672EGP', 'Catalan', 'Quality-focused multi-state utilisation', 35);
insert into Disciplina (codigo_disciplina, nome, ementa, creditos) values ('462WRO', 'Arabic', 'Total explicit definition', 22);
insert into Disciplina (codigo_disciplina, nome, ementa, creditos) values ('325BPU', 'Tsonga', 'Compatible real-time data-warehouse', 35);
insert into Disciplina (codigo_disciplina, nome, ementa, creditos) values ('929LCA', 'Gagauz', 'Profound intermediate service-desk', 34);
insert into Disciplina (codigo_disciplina, nome, ementa, creditos) values ('301GIG', 'Northern Sotho', 'Quality-focused fault-tolerant open system', 32);
insert into Disciplina (codigo_disciplina, nome, ementa, creditos) values ('658NCV', 'Indonesian', 'Fundamental grid-enabled adapter', 57);
insert into Disciplina (codigo_disciplina, nome, ementa, creditos) values ('509VAH', 'Mongolian', 'Compatible neutral customer loyalty', 28);
insert into Disciplina (codigo_disciplina, nome, ementa, creditos) values ('800LIX', 'Bengali', 'Ameliorated user-facing conglomeration', 36);
insert into Disciplina (codigo_disciplina, nome, ementa, creditos) values ('110RHJ', 'Czech', 'Seamless impactful local area network', 20);
insert into Disciplina (codigo_disciplina, nome, ementa, creditos) values ('553WNU', 'Moldovan', 'Fundamental neutral adapter', 30);
insert into Disciplina (codigo_disciplina, nome, ementa, creditos) values ('265YFO', 'Macedonian', 'Seamless dynamic productivity', 24);
insert into Disciplina (codigo_disciplina, nome, ementa, creditos) values ('190BIX', 'Malayalam', 'Sharable human-resource budgetary management', 59);
insert into Disciplina (codigo_disciplina, nome, ementa, creditos) values ('319TFK', 'Tamil', 'Synergistic empowering encryption', 60);
insert into Disciplina (codigo_disciplina, nome, ementa, creditos) values ('853UNN', 'Amharic', 'Programmable explicit encryption', 49);
insert into Disciplina (codigo_disciplina, nome, ementa, creditos) values ('206SSY', 'Kashmiri', 'Inverse disintermediate projection', 37);
insert into Disciplina (codigo_disciplina, nome, ementa, creditos) values ('590IED', 'Moldovan', 'Visionary zero administration approach', 55);
insert into Disciplina (codigo_disciplina, nome, ementa, creditos) values ('195WKH', 'Māori', 'Cloned homogeneous instruction set', 60);
insert into Disciplina (codigo_disciplina, nome, ementa, creditos) values ('817KZQ', 'Finnish', 'Self-enabling 5th generation project', 15);
insert into Disciplina (codigo_disciplina, nome, ementa, creditos) values ('164YQY', 'Northern Sotho', 'Future-proofed transitional open system', 53);
insert into Disciplina (codigo_disciplina, nome, ementa, creditos) values ('329SIW', 'Polish', 'Ergonomic uniform model', 59);
insert into Disciplina (codigo_disciplina, nome, ementa, creditos) values ('878BCK', 'Romanian', 'Networked coherent process improvement', 24);
insert into Disciplina (codigo_disciplina, nome, ementa, creditos) values ('965ZGT', 'Somali', 'Visionary interactive alliance', 50);
insert into Disciplina (codigo_disciplina, nome, ementa, creditos) values ('898IPX', 'Mongolian', 'Upgradable leading edge strategy', 23);
insert into Disciplina (codigo_disciplina, nome, ementa, creditos) values ('376ZSL', 'Moldovan', 'Operative dynamic attitude', 52);
insert into Disciplina (codigo_disciplina, nome, ementa, creditos) values ('914DRB', 'Kashmiri', 'Triple-buffered non-volatile policy', 31);
insert into Disciplina (codigo_disciplina, nome, ementa, creditos) values ('120GOA', 'Tetum', 'Enhanced non-volatile productivity', 19);
